name = "catpablog-backend"
main = "index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "catpablog-backend"
routes = [
  { pattern = "api.catpablog.example.com", zone_name = "example.com" }
]

[vars]
NODE_ENV = "production"
